OP_CODE = {
    0x00 : "Empty",
    0x01 : "Nop",
    0x02 : "Param op1",
    0x03 : "BeginFunction op1, op2",
    0x04 : "EndFunction",
    0x05 : "Call op1",
    0x06 : "Return",
    0x07 : "ReturnVal",
    0x08 : "GetParam op1, op2",
    0x09 : "SetParam op1, op2",
    0x0A : "GetReturn op1",
    0x0B : "NativeParam op1",
    0x0C : "NativeCall op1",
    0x0D : "NativeGetReturn op1",
    0x0E : "Goto op1",
    0x0F : "IfNotZeroGoto op1, op2",
    0x10 : "IfZeroGoto op1, op2 (UNUSED)",
    0x11 : "Affect0Integer op1, op2",
    0x12 : "Affect0Float op1, op2 (UNUSED)",
    0x13 : "Affect0ConstantInteger op1, op2",
    0x14 : "Affect0ConstantFloat op1, op2",
    0x15 : "Affect1MinusInteger op1, op2",
    0x16 : "Affect1MinusFloat op1, op2 (UNUSED)",
    0x17 : "Affect1CastToInteger op1, op2 (UNUSED)",
    0x18 : "Affect1CastToFloat op1, op2 (UNUSED)",
    0x19 : "Affect2IntegerAdd op1, op2, op3",
    0x1A : "Affect2IntegerSub op1, op2, op3",
    0x1B : "Affect2IntegerMult op1, op2, op3",
    0x1C : "Affect2IntegerDiv op1, op2, op3",
    0x1D : "Affect2FloatAdd op1, op2, op3 (UNUSED)",
    0x1E : "Affect2FloatSub op1, op2, op3 (UNUSED)",
    0x1F : "Affect2FloatMult op1, op2, op3 (UNUSED)",
    0x20 : "Affect2FloatDiv op1, op2, op3 (UNUSED)",
    0x21 : "Affect2IntegerInfEq op1, op2, op3",
    0x22 : "Affect2IntegerInf op1, op2, op3",
    0x23 : "Affect2IntegerSupEq op1, op2, op3",
    0x24 : "Affect2IntegerSup op1, op2, op3",
    0x25 : "Affect2IntegerNEq op1, op2, op3",
    0x26 : "Affect2IntegerEq op1, op2, op3",
    0x27 : "Affect2FloatInfEq op1, op2, op3 (UNUSED)",
    0x28 : "Affect2FloatInf op1, op2, op3 (UNUSED)",
    0x29 : "Affect2FloatSupEq op1, op2, op3 (UNUSED)",
    0x2A : "Affect2FloatSup op1, op2, op3 (UNUSED)",
    0x2B : "Affect2FloatNEq op1, op2, op3 (UNUSED)",
    0x2C : "Affect2FloatEq op1, op2, op3 (UNUSED)",
}


NATIVE_FUNCTIONS = {
    0x00 : "StartDialog                       - (int dialogId)",
    0x01 : "SetCameraScrollTo                 - (object)",
    0x02 : "SetCameraScrollSlowlyTo           - (object | float)",
    0x03 : "SetCameraJumpTo                   - (object)",
    0x04 : "SetZoomLevel                      - (float)",
    0x05 : "DisplayMap                        - (bool)",
    0x06 : "PrintConsole                      - (int)",
    0x07 : "DisplayConsole                    - ()",
    0x08 : "IsActorEqual                      - (object | object)",
    0x09 : "IsAnyCivilianDead                 - ()",
    0x0A : "IsAnyEnemyDead                    - ()",
    0x0B : "GetOverallEnemyAlert              - ()",
    0x0C : "GetOverallCivilianAlert           - ()",
    0x0D : "FreezeAll                         - (bool)",
    0x0E : "InflictPain                       - (actor | int damage | bool knockOut)",
    0x0F : "GetNumberOfActorsInEngine         - ()",
    0x10 : "GetActor                          - (int actorId)",
    0x11 : "GetLocation                       - (int locationId)",
    0x12 : "IsActorAnimation                  - (object)",
    0x13 : "IsActorObject                     - (actor)",
    0x14 : "IsActorCharacter                  - (actor)",
    0x15 : "IsActorPC                         - (actor)",
    0x16 : "IsActorNPC                        - (actor)",
    0x17 : "IsActorEnemy                      - (actor)",
    0x18 : "IsActorCivilian                   - (actor)",
    0x19 : "IsActorAnimal                     - (actor)",
    0x1A : "IsNull                            - (object)",
    0x1B : "GetActorPosture                   - (actor)",
    0x1C : "SetActorPosture                   - (actor | int)",
    0x1D : "GetCooper                         - ()",
    0x1E : "GetSam                            - ()",
    0x1F : "GetDoc                            - ()",
    0x20 : "GetKate                           - ()",
    0x21 : "GetSanchez                        - ()",
    0x22 : "GetMia                            - ()",
    0x23 : "GetActorLocation                  - (actor)",
    0x24 : "SetActorLocation                  - (actor | location)",
    0x25 : "IsInside                          - (actor | location)",
    0x26 : "IsInsideBuilding                  - (actor | int)",
    0x27 : "GetAnyActorInside                 - (location)",
    0x28 : "SwitchProfile                     - (object)",
    0x29 : "GetMovementStyle                  - (actor)",
    0x2A : "Deactivate                        - (actor)",
    0x2B : "Activate                          - (actor)",
    0x2C : "SetActionAvailable                - (actor | int action | bool)",
    0x2D : "IsActionAvailable                 - (actor | int action)",
    0x2E : "SetPersistentProperty             - (actor | int property | int)",
    0x2F : "GetPersistentProperty             - (actor | int property)",
    0x30 : "SetAIAlertStatus                  - (actor | int)",
    0x31 : "GetAIAlertStatus                  - (actor)",
    0x32 : "SetAIState                        - (actor | int)",
    0x33 : "GetAIState                        - (actor)",
    0x34 : "SetAIAttitude                     - (actor | int)",
    0x35 : "GetAIAttitude                     - (actor)",
    0x36 : "SetAILevel                        - (actor | int | int)",
    0x37 : "SetViewCone                       - (actor | int)",
    0x38 : "StareActor                        - (actor | object | bool)",
    0x39 : "StareLocation                     - (actor | object | bool)",
    0x3A : "AssignPath                        - (actor | int)",
    0x3B : "AssignPost                        - (actor | location | int)",
    0x3C : "LockAI                            - (actor | bool)",
    0x3D : "UnlockAI                          - (actor)",
    0x3E : "ForceBattleDecision               - (actor | int)",
    0x3F : "MakeNoise                         - (object | int)",
    0x40 : "Freeze                            - (actor | bool)",
    0x41 : "GetTheRider                       - (object)",
    0x42 : "GetTheHorse                       - (object)",
    0x43 : "IsAnimationActive                 - (object)",
    0x44 : "SetAnimationState                 - (object | bool)",
    0x45 : "IsPatchApplied                    - (int)",
    0x46 : "ApplyPatch                        - (int)",
    0x47 : "IsHorseUsed                       - (object)",
    0x48 : "StartSequenceRecording            - ()",
    0x49 : "EndSequenceRecording              - ()",
    0x4A : "IncrementSequenceLevel            - ()",
    0x4B : "Start                             - ()",
    0x4C : "Thanx                             - ()",
    0x4D : "Then                              - ()",
    0x4E : "RecordCameraScrollTo              - (location)",
    0x4F : "RecordCameraJumpTo                - (location)",
    0x50 : "RecordSetZoom                     - (float)",
    0x51 : "RecordDisplayMap                  - (bool)",
    0x52 : "RecordStartBriefing               - ()",
    0x53 : "RecordEndBriefing                 - ()",
    0x54 : "RecordActionAvailable             - (object | int | bool)",
    0x55 : "RecordCharacterAvailable          - (object | bool)",
    0x56 : "RecordLockCameraOn                - (object)",
    0x57 : "RecordClearCameraOn               - ()",
    0x58 : "RecordPlayDialog                  - (int)",
    0x59 : "RecordMove                        - (object | object | int)",
    0x5A : "RecordLeaveGame                   - (object | object | int)",
    0x5B : "RecordTurnTo                      - (object | object)",
    0x5C : "RecordMountHorse                  - (object | object)",
    0x5D : "RecordDismountHorse               - (object | object)",
    0x5E : "RecordFireAt                      - (object | object)",
    0x5F : "RecordPlayAnim                    - (object | int)",
    0x60 : "RecordPlayAnimLoop                - (object | int)",
    0x61 : "RecordPlayAnimFreeze              - (actor | int)",
    0x62 : "RecordLockAI                      - (object)",
    0x63 : "RecordUnlockAI                    - ()",
    0x64 : "RecordLockUser                    - ()",
    0x65 : "RecordUnLockUser                  - (object)",
    0x66 : "RecordTimer                       - (int ticks)",
    0x67 : "RecordSeekActor                   - (object | object | int | float)",
    0x68 : "RecordStopSeek                    - (object)",
    0x69 : "RecordSendCustomEvent             - (object | int)",
    0x6A : "RecordAction                      - (object | int | int)",
    0x6B : "InitGlobal                        - (int | int)",
    0x6C : "SetGlobal                         - (int | int)",
    0x6D : "GetGlobal                         - (int)",
    0x6E : "SuspendAllSoundSources            - ()",
    0x6F : "ResumeAllSoundSources             - ()",
    0x70 : "GetSoundSource                    - (int)",
    0x71 : "ActivateSoundSource               - (object)",
    0x72 : "DeactivateSoundSource             - (object)",
    0x73 : "DestroySoundSource                - (object)",
    0x74 : "CleanFromHisBuildingBeforeTelepor - (actor)",
    0x75 : "AddToHisNewBuildingAfterTeleporto - (actor)",
    0x76 : "CleanFromScriptZoneBeforeTeleport - (actor | object)",
    0x77 : "AddToScriptZoneAfterTeleport      - (actor | object)",
    0x78 : "LockNearestDoorForPCs             - (object | bool)",
    0x79 : "LockNearestDoorForVillains        - (object | bool)",
    0x7A : "LockNearestDoorForCivilians       - (object | bool)",
    0x7B : "This                              - ()",
    0x7C : "GetActorDirection                 - (actor)",
    0x7D : "SetActorDirection                 - (actor | int directionId)",
    0x7E : "StopActor                         - (actor)",
    0x7F : "GetDistance                       - (object | object)",
    0x80 : "GetCurrentAction                  - (object)",
    0x81 : "IsActorCart                       - (actor)",
    0x82 : "SetPathWalkingStyle               - (object | int)",
    0x83 : "RecordReplaceAnim                 - (object | int | int)",
    0x84 : "RecordRestoreAnim                 - (object | int)",
    0x85 : "Sees                              - (actor | actor)",
    0x86 : "GetActorIndex                     - (actor)",
    0x87 : "JoinArmy                          - (object | int)",
    0x88 : "DeclareWar                        - (object)",
    0x89 : "GetArmy                           - (object)",
    0x8A : "SetSoldierSeesSoldier             - (object | object | bool)",
    0x8B : "SetSoldierSeesArmy                - (object | int | bool)",
    0x8C : "SetArmySeesSoldier                - (int | object | bool)",
    0x8D : "SetArmySeesArmy                   - (int | int | bool)",
    0x8E : "GetNumberOfVisibleSoldiers        - (object)",
    0x8F : "GetVisibleSoldier                 - (object | int)",
    0x90 : "GetNearestVisibleSoldier          - (object)",
    0x91 : "CreateListOfRecentlySeenSoldierse - (object | int)",
    0x92 : "GetNumberOfRecentlySeenSoldiersrs - ()",
    0x93 : "GetRecentlySeenSoldier            - (int)",
    0x94 : "GetNearestRecentlySeenSoldier     - ()",
    0x95 : "PutSnakeOnMap                     - (object)",
    0x96 : "PutWatchOnMap                     - (object)",
    0x97 : "RecordTakeCorpse                  - (object | object | int)",
    0x98 : "RecordMoveIntoBuilding            - (object | object | int)",
    0x99 : "RecordCameraMoveTo                - (location | int speed)",
    0x9A : "RecordEnterBarrel                 - (object | object | int)",
    0x9B : "RecordLeaveBarrel                 - (object)",
    0x9C : "RecordEnterGame                   - (object | object | object | int)",
    0x9D : "RecordLeaveCorpse                 - (object)",
    0x9E : "SetUltimateWillOnHorse            - (object | bool)",
    0x9F : "CallKnife                         - ()",
    0xA0 : "ResetAnim                         - (object)",
    0xA1 : "RecordJumpOnHorse                 - (object | object)",
    0xA2 : "EnableHorseUseFor                 - (object | bool)",
    0xA3 : "DefineAnimalAlert                 - (object | object | int)",
    0xA4 : "RecordTieCorpse                   - (object | object | int)",
    0xA5 : "PutActorInBuilding                - (actor | int)",
    0xA6 : "SetBuildingActive                 - (int | bool)",
    0xA7 : "RecordStartMobileElement          - (int)",
    0xA8 : "RecordStopMobileElement           - (int)",
    0xA9 : "SetNearestDoorDocLockPickable     - (object | bool)",
    0xAA : "DisplayHint                       - (int)",
    0xAB : "HideHint                          - ()",
    0xAC : "PutActorInBarrel                  - (actor | object)",
    0xAD : "SetSkipData                       - (int)",
    0xAE : "ForbidHorseForAI                  - (object | bool)",
    0xAF : "RecordSpeak                       - (object | int)",
    0xB0 : "RecordFireLocation                - (object | object)",
    0xB1 : "Rand                              - (int)",
    0xB2 : "ResetPatch                        - (int)",
    0xB3 : "PrototypeFilterEvent              - (object | object | int)",
    0xB4 : "AddSentence                       - (int)",
    0xB5 : "DoneSentence                      - (int)",
    0xB6 : "ChooseVictoryDefeatText           - (int)",
    0xB7 : "EnableViewCone                    - (object)",
    0xB8 : "SetPCAsUnwantedFor                - (object | object)",
    0xB9 : "SpecialAutorisation               - (object | bool | object)",
    0xBA : "RecordSpeakPC                     - (object | int)",
    0xBB : "SelectPC                          - (int)",
    0xBC : "SetBuildingAsTrainWaggon          - (int | int)",
    0xBD : "RecordSeekActorCustomEvent        - (object | object | int | float | object | int)",
    0xBE : "ActivateDoorMouseSector           - (bool | object)",
    0xBF : "GetOutlineDisplay                 - ()",
    0xC0 : "SetOutlineDisplay                 - (bool)",
    0xC1 : "CustomizeMinimapDisplay           - (actor | int)",
    0xC2 : "GetDoorStateForPC                 - (object)",
    0xC3 : "RecordLeaveGameDirectionnal       - (object | int | int)",
    0xC4 : "SetCorpseExistsInBuilding         - (object)",
    0xC5 : "ForceCheckVictory                 - ()",
    0xC6 : "ForceEmergencyBoxForMotionAreaa   - (object)",
    0xC7 : "SetUserInputPossibleForHorse      - (object | bool)",
}